### ISSUE TITLE
How to use my css style with this addon

### ISSUE THREAD

**Issue by dinagr** [mharris717/ember-cli-pagination#194]
Hello,

I would like to be able to use my style with this addon.
How can I do it?

Thanks a lot,
Dina

**Comment by stephencarr** [comment]
+1 for this

**Comment by dandy91** [comment]
i want to solve this issue too !!

**Comment by broerse** [comment]
You can style this: https://github.com/mharris717/ember-cli-pagination/blob/master/addon/templates/components/page-numbers.hbs

If you want to add a First and Last page do this `{{page-numbers content=content showFL=true}}`

**Comment by broerse** [comment]
PR's to the readme are welcome if this is not clear.

**Comment by broerse** [comment]
@dinagr @stephencarr  Sorry I totally missed seeing this issue. Worked hard to remove the binding deprecation and was not focused on other issues.

**Comment by dandy91** [comment]
yeah.. i realized that i can edit the class in handlebars file..... but if i installed this addon from the command and i haven't this file in my project ! what's can i do ?!

**Comment by broerse** [comment]
@dandy91 In your app/styles just add something like this:

``` css
.pagination > li > a,
.pagination > li > span,
.pagination > li:first-child > a,
.pagination > li:first-child > span {
  background-color: red;
}

```
